### ISSUE TITLE
Remove Contact/Help link

### ISSUE THREAD

**Issue by jeffnm** [ndlibersa/reports#9]
The contact/help mailto: link does not appear on any other module and does not have any way for user to customized it without directly editing the code.  

I think we should remove it.

If we want to add a contact help link to every page of every module in 2.0, then that should be a configuration setting that allows administrators to enter their preferred contact email.

**Comment by coraladmin** [comment]
Removing makes sense to me.

**Comment by PaulPoulain** [comment]
Removing makes sense to me.

(and I think we can think of a global Coral strategy for this kind of things once all repos will be merged into only one. Will be easier to define & code)
